In [29]:
##Scraping data from a website##

In [30]:
from bs4 import BeautifulSoup
import requests

In [31]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [44]:

pd.set_option("display.max_rows", None)

In [54]:
table = soup.find_all('table')[1]  # we scrape by inspetcing the website and find what we need and try to search a title tag or table tag and extract it here
print(table) # we take out the table data from the soup (which has the whole page data)

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD billions)
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Cargill" title="Cargill">Cargill</a>
</td>
<td>Food industry
</td>
<td style="text-align:center;">177
</td>
<td style="text-align:center;">160,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>2
</td>
<td><a class="mw-redirect" href="/wiki/Koch_Industries" title="Koch Industries">Koch Industries</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">125
</td>
<td style="text-align:center;">120,000
</td>
<td><a href="/wiki/Wichita,_Kansas" title="Wichita, Kansas">Wichita, Kansas</a>
</td></tr>
<tr>
<td>3
</td>
<td><a class="mw-redirect" href="/wiki/Publix_Super_Markets" title="Publix Super Markets">Publix Super Markets</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">54.5
</td>
<td style="text-align:center;">250,000
</td>
<td><a href="/wiki/Winter_Haven,_Florida" title="Winter Haven, Florida">Winter Haven, Florida</a>
</td></tr>
<tr>
<td>4
</td>
<td><a class="mw-redirect" href="/wiki/Mars,_Incorporated" title="Mars, Incorporated">Mars, Incorporated</a>
</td>
<td>Food industry
</td>
<td style="text-align:center;">47
</td>
<td style="text-align:center;">140,000
</td>
<td><a href="/wiki/McLean,_Virginia" title="McLean, Virginia">McLean, Virginia</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/H-E-B" title="H-E-B">H-E-B</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">43.6
</td>
<td style="text-align:center;">145,000
</td>
<td><a class="mw-redirect" href="/wiki/San_Antonio,_Texas" title="San Antonio, Texas">San Antonio, Texas</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Reyes_Holdings" title="Reyes Holdings">Reyes Holdings</a>
</td>
<td><a href="/wiki/Wholesaling" title="Wholesaling">Wholesaling</a>
</td>
<td style="text-align:center;">40
</td>
<td style="text-align:center;">36,000
</td>
<td><a href="/wiki/Rosemont,_Illinois" title="Rosemont, Illinois">Rosemont, Illinois</a>
</td></tr>
<tr>
<td>7
</td>
<td><a href="/wiki/Enterprise_Holdings" title="Enterprise Holdings">Enterprise Holdings</a>
</td>
<td><a href="/wiki/Car_rental" title="Car rental">Car rental</a>
</td>
<td style="text-align:center;">35
</td>
<td style="text-align:center;">90,000
</td>
<td><a href="/wiki/Clayton,_Missouri" title="Clayton, Missouri">Clayton, Missouri</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/C%26S_Wholesale_Grocers" title="C&amp;S Wholesale Grocers">C&amp;S Wholesale Grocers</a>
</td>
<td>Wholesaling
</td>
<td style="text-align:center;">34.7
</td>
<td style="text-align:center;">15,000
</td>
<td><a href="/wiki/Keene,_New_Hampshire" title="Keene, New Hampshire">Keene, New Hampshire</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/Love%27s" title="Love's">Love's</a>
</td>
<td>Petroleum industry and Retail
</td>
<td style="text-align:center;">26.5
</td>
<td style="text-align:center;">40,000
</td>
<td><a class="mw-redirect" href="/wiki/Oklahoma_City,_Oklahoma" title="Oklahoma City, Oklahoma">Oklahoma City, Oklahoma</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Southern_Glazer%27s_Wine_and_Spirits" title="Southern Glazer's Wine and Spirits">Southern Glazer's Wine and Spirits</a>
</td>
<td>Food industry
</td>
<td style="text-align:center;">26.0
</td>
<td style="text-align:center;">24,000
</td>
<td><a href="/wiki/Miramar,_Florida" title="Miramar, Florida">Miramar, Florida</a>
</td></tr></tbody></table>

In [60]:
world_titles = table.find_all('th')

In [61]:
world_titles

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD billions)
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [62]:
world_tables_titles = [title.text.strip() for title in world_titles]
print(world_tables_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD billions)', 'Employees', 'Headquarters']

In [63]:
df = pd.DataFrame(columns = world_tables_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD billions), Employees, Headquarters]
Index: []

In [65]:
column_data = table.find_all(['th', 'td'])

In [81]:
from bs4 import BeautifulSoup

# Assuming 'page.text' contains the HTML content of the page
soup = BeautifulSoup(page.text, 'html.parser')

# Find the target table
target_table = soup.find('table', {'class': 'wikitable sortable'})

# Extract all the rows from the table
rows = target_table.find_all('tr')

# Initialize an empty list to store the extracted row data
data_rows = []

# Extract data from each row
for row in rows:
    # Extract both header and data cells
    columns = row.find_all(['th', 'td'])  
    data = [col.get_text(strip=True) for col in columns]
    
    # Print data to debug and check the extracted columns
    print(f"Extracted data: {data}")
    
    # Append data to data_rows
    data_rows.append(data)

# Now, let's print data_rows to see what we have before putting it into a DataFrame
print(data_rows)

Extracted data: ['Rank', 'Name', 'Industry', 'Revenue(USD millions)', 'Revenue growth', 'Employees', 'Headquarters']
Extracted data: ['1', 'Walmart', 'Retail', '648,125', '6.0%', '2,100,000', 'Bentonville, Arkansas']
Extracted data: ['2', 'Amazon', 'Retail andcloud computing', '574,785', '11.9%', '1,525,000', 'Seattle, Washington']
Extracted data: ['3', 'Apple', 'Electronics industry', '383,482', '-2.8%', '161,000', 'Cupertino, California']
Extracted data: ['4', 'UnitedHealth Group', 'Healthcare', '371,622', '14.6%', '440,000', 'Minnetonka, Minnesota']
Extracted data: ['5', 'Berkshire Hathaway', 'Conglomerate', '364,482', '20.7%', '396,500', 'Omaha, Nebraska']
Extracted data: ['6', 'CVS Health', 'Healthcare', '357,776', '10.9%', '259,500', 'Woonsocket, Rhode Island']
Extracted data: ['7', 'ExxonMobil', 'Petroleum industry', '344,582', '-16.7%', '61,500', 'Spring, Texas']
Extracted data: ['8', 'Alphabet', 'Technologyand cloud computing', '307,394', '8.7%', '182,502', 'Mountain View, California']
Extracted data: ['9', 'McKesson Corporation', 'Health', '276,711', '4.8%', '48,000', 'Irving, Texas']
Extracted data: ['10', 'Cencora', 'Pharmacy wholesale', '262,173', '9.9%', '44,000', 'Conshohocken, Pennsylvania']
Extracted data: ['11', 'Costco', 'Retail', '242,290', '6.8%', '316,000', 'Issaquah, Washington']
Extracted data: ['12', 'JPMorgan Chase', 'Financial services', '239,425', '54.7%', '309,926', 'New York City, New York']
Extracted data: ['13', 'Microsoft', 'Technology and cloud computing', '211,915', '6.9%', '221,000', 'Redmond, Washington']
Extracted data: ['14', 'Cardinal Health', 'Healthcare', '205,012', '13.0%', '47,520', 'Dublin, Ohio']
Extracted data: ['15', 'Chevron Corporation', 'Petroleum industry', '200,949', '-18.4%', '45,600', 'San Ramon, California']
Extracted data: ['16', 'Cigna', 'Health insurance', '195,265', '8.2%', '71,413', 'Bloomfield, Connecticut']
Extracted data: ['17', 'Ford Motor Company', 'Automotive industry', '176,191', '11.5%', '177,000', 'Dearborn, Michigan']
Extracted data: ['18', 'Bank of America', 'Financials', '171,912', '49.4%', '212,985', 'Charlotte, North Carolina']
Extracted data: ['19', 'General Motors', 'Automotive industry', '171,842', '9.6%', '163,000', 'Detroit, Michigan']
Extracted data: ['20', 'Elevance Health', 'Healthcare', '171,340', '9.4%', '104,900', 'Indianapolis, Indiana']
Extracted data: ['21', 'Citigroup', 'Financials', '156,820', '55.1%', '237,925', 'New York City, New York']
Extracted data: ['22', 'Centene', 'Healthcare', '153,999', '6.5%', '67,700', 'St. Louis, Missouri']
Extracted data: ['23', 'The Home Depot', 'Retail', '152,669', '-3.0%', '463,100', 'Atlanta, Georgia']
Extracted data: ['24', 'Marathon Petroleum', 'Petroleum industry', '150,307', '-16.5%', '18,200', 'Findlay, Ohio']
Extracted data: ['25', 'Kroger', 'Retail', '150,039', '-3.6%', '414,000', 'Cincinnati, Ohio']
Extracted data: ['26', 'Phillips 66', 'Petroleum industry', '149,890', '-14.7%', '14,000', 'Houston, Texas']
Extracted data: ['27', 'Fannie Mae', 'Financials', '141,240', '16.2%', '8,100', 'Washington, D.C.']
Extracted data: ['28', 'Walgreens Boots Alliance', 'Pharmaceutical industry', '139,081', '4.8%', '268,500', 'Deerfield, Illinois']
Extracted data: ['29', 'Valero Energy', 'Petroleum industry', '139,001', '-18.8%', '9,987', 'San Antonio, Texas']
Extracted data: ['30', 'Meta Platforms', 'Technology', '134,902', '15.7%', '67,317', 'Menlo Park, California']
Extracted data: ['31', 'Verizon Communications', 'Telecommunications', '133,974', '-2.1%', '105,400', 'New York City, New York']
Extracted data: ['32', 'AT&T', 'Conglomerateand telecommunications', '122,428', '1.4%', '150,470', 'Dallas, Texas']
Extracted data: ['33', 'Comcast', 'Telecommunications', '121,572', '0.1%', '186,000', 'Philadelphia, Pennsylvania']
Extracted data: ['34', 'Wells Fargo', 'Financials', '115,340', '39.2%', '226,000', 'San Francisco, California']
Extracted data: ['35', 'Goldman Sachs', 'Financials', '108,418', '57.8%', '45,300', 'New York City, New York']
Extracted data: ['36', 'Freddie Mac', 'Financials', '108,050', '24.6%', '8,020', 'McLean, Virginia']
Extracted data: ['37', 'Target Corporation', 'Retail', '107,412', '-1.6%', '415,000', 'Minneapolis, Minnesota']
Extracted data: ['38', 'Humana', 'Health insurance', '106,374', '14.5%', '67,600', 'Louisville, Kentucky']
Extracted data: ['39', 'State Farm', 'Financials', '104,199', '16.6%', '65,054', 'Bloomington, Illinois']
Extracted data: ['40', 'Tesla', 'Automotive and energy', '96,773', '18.8%', '140,473', 'Austin, Texas']
Extracted data: ['41', 'Morgan Stanley', 'Financials', '96,194', '45.9%', '80,006', 'New York City, New York']
Extracted data: ['42', 'Johnson & Johnson', 'Pharmaceutical industry', '95,195', '0.3%', '131,900', 'New Brunswick, New Jersey']
Extracted data: ['43', 'Archer Daniels Midland', 'Food industry', '93,935', '-7.5%', '41,008', 'Chicago, Illinois']
Extracted data: ['44', 'PepsiCo', 'Beverage', '91,471', '5.9%', '318,000', 'Purchase, New York']
Extracted data: ['45', 'United Parcel Service', 'Transportation', '90,958', '-9.3%', '382,550', 'Atlanta, Georgia']
Extracted data: ['46', 'FedEx', 'Transportation', '90,155', '-3.6%', '446,400', 'Memphis, Tennessee']
Extracted data: ['47', 'The Walt Disney Company', 'Media', '88,898', '7.5%', '199,125', 'Burbank, California']
Extracted data: ['48', 'Dell Technologies', 'Technology', '88,425', '-13.6%', '120,000', 'Round Rock, Texas']
Extracted data: ['49', "Lowe's", 'Retail', '86,377', '-11.0%', '226,000', 'Mooresville, North Carolina']
Extracted data: ['50', 'Procter & Gamble', 'Consumer products manufacturing', '82,006', '2.3%', '107,000', 'Cincinnati, Ohio']
Extracted data: ['51', 'Energy Transfer Partners', 'Petroleum industry', '78,586', '-12.6%', '13,786', 'Dallas, Texas']
Extracted data: ['52', 'Boeing', 'Aerospaceanddefense', '77,794', '16.8%', '171,000', 'Arlington County, Virginia']
Extracted data: ['53', 'Albertsons', 'Retail', '77,650', '8.0%', '198,650', 'Boise, Idaho']
Extracted data: ['54', 'Sysco', 'Food service', '76,325', '11.2%', '71,750', 'Houston, Texas']
Extracted data: ['55', 'RTX Corporation', 'Conglomerate', '68,920', '2.8%', '185,000', 'Arlington County, Virginia']
Extracted data: ['56', 'General Electric', 'Conglomerate', '67,954', '-11.2%', '125,000', 'Boston, Massachusetts']
Extracted data: ['57', 'Lockheed Martin', 'Aerospace and defense', '67,571', '2.4%', '122,000', 'Bethesda, Maryland']
Extracted data: ['58', 'American Express', 'Financial', '67,364', '21.1%', '74,600', 'New York City, New York']
Extracted data: ['59', 'Caterpillar', 'Machinery', '67,060', '12.8%', '113,200', 'Deerfield, Illinois']
Extracted data: ['60', 'MetLife', 'Financials', '66,905', '-4.3%', '45,000', 'New York City, New York']
Extracted data: ['61', 'HCA Healthcare', 'Healthcare', '64,968', '7.9%', '265,000', 'Nashville, Tennessee']
Extracted data: ['62', 'Progressive Corporation', 'Insurance', '62,109', '25.2%', '61,432', 'Mayfield Village, Ohio']
Extracted data: ['63', 'IBM', 'Technology and cloud computing', '61,860', '-16.3%', '296,600', 'Armonk, New York']
Extracted data: ['64', 'John Deere', 'Agriculture manufacturing', '61,251', '16.5%', '82,956', 'Moline, Illinois']
Extracted data: ['65', 'Nvidia', 'Technology', '60,922', '125.9%', '29,600', 'Santa Clara, California']
Extracted data: ['66', 'StoneX Group', 'Financials', '60,856', '-7.8%', '4,137', 'New York City, New York']
Extracted data: ['67', 'Merck & Co.', 'Pharmaceutical industry', '60,115', '1.4%', '71,000', 'Kenilworth, New Jersey']
Extracted data: ['68', 'ConocoPhillips', 'Petroleum industry', '58,574', '-28.7%', '9,900', 'Houston, Texas']
Extracted data: ['69', 'Pfizer', 'Pharmaceutical industry', '58,496', '-41.7%', '88,000', 'New York City, New York']
Extracted data: ['70', 'Delta Air Lines', 'Airline', '58,048', '14.8%', '103,000', 'Atlanta, Georgia']
Extracted data: ['71', 'TD Synnex', 'Infotech', '57,555', '-7.7%', '28,000', 'Clearwater, Florida']
Extracted data: ['72', 'Publix', 'Retail', '57,534', '4.7%', '253,000', 'Lakeland, Florida']
Extracted data: ['73', 'Allstate', 'Insurance', '57,094', '11.1%', '53,200', 'Northfield Township, Cook County, Illinois']
Extracted data: ['74', 'Cisco', 'Telecom hardware manufacturing', '56,998', '10.6%', '84,900', 'San Jose, California']
Extracted data: ['75', 'Nationwide Mutual Insurance Company', 'Financial', '54,609', '6.1%', '24,118', 'Columbus, Ohio']
Extracted data: ['76', 'Charter Communications', 'Telecommunications', '54,607', '1.1%', '101,100', 'Stamford, Connecticut']
Extracted data: ['77', 'AbbVie', 'Pharmaceutical industry', '54,317', '-6.4%', '50,000', 'Lake Bluff, Illinois']
Extracted data: ['78', 'New York Life Insurance Company', 'Insurance', '54,317', '14.2%', '15,384', 'New York City, New York']
Extracted data: ['79', 'Intel', 'Technology', '54,228', '-14.0%', '124,800', 'Santa Clara, California']
Extracted data: ['80', 'TJX', 'Retail', '49,936', '2.9%', '329,000', 'Framingham, Massachusetts']
Extracted data: ['81', 'Prudential Financial', 'Financials', '53,979', '-10.1%', '40,366', 'Newark, New Jersey']
Extracted data: ['82', 'HP', 'Technology', '53,718', '-14.5%', '58,000', 'Palo Alto, California']
Extracted data: ['83', 'United Airlines', 'Airline', '53,717', '19.5%', '103,300', 'Chicago, Illinois']
Extracted data: ['84', 'Performance Food Group', 'Food processing', '53,355', '13.1%', '34,825', 'Richmond, Virginia']
Extracted data: ['85', 'Tyson Foods', 'Food processing', '52,788', '-0.8%', '139,000', 'Springdale, Arkansas']
Extracted data: ['86', 'American Airlines', 'Airline', '52,788', '7.8%', '132,100', 'Fort Worth, Texas']
Extracted data: ['87', 'Liberty Mutual', 'Insurance', '52,612', '5.3%', '45,000', 'Boston, Massachusetts']
Extracted data: ['88', 'Nike', 'Apparel', '51,217', '9.6%', '83,700', 'Beaverton, Oregon']
Extracted data: ['89', 'Oracle Corporation', 'Technology', '49,954', '17.7%', '164,000', 'Austin, Texas']
Extracted data: ['90', 'Enterprise Products', 'Petroleum industry', '49,715', '-14.6%', '7,500', 'Houston, Texas']
Extracted data: ['91', 'Capital One Financial', 'Financials', '49,484', '29.0%', '51,987', 'Richmond, Virginia']
Extracted data: ['92', 'Plains All American Pipeline', 'Petroleum industry', '48,712', '-15.1%', '4,200', 'Houston, Texas']
Extracted data: ['93', 'World Kinect Corporation', 'Energy trading', '47,711', '-19.2%', '5,289', 'Doral,Florida']
Extracted data: ['94', 'AIG', 'Insurance', '46,802', '-17.1%', '25,200', 'New York City, New York']
Extracted data: ['95', 'Coca-Cola', 'Beverage', '45,754', '6.4%', '79,100', 'Atlanta, Georgia']
Extracted data: ['96', 'TIAA', 'Financials', '45,735', '11.8%', '16,023', 'New York City, New York']
Extracted data: ['97', 'CHS', 'Agriculture cooperative', '45,590', '-4.6%', '10,609', 'Inver Grove Heights, Minnesota']
Extracted data: ['98', 'Bristol-Myers Squibb', 'Pharmaceutical industry', '45,006', '-2.5%', '34,100', 'New York City,New York']
Extracted data: ['99', 'Dow Chemical Company', 'Chemical industry', '44,622', '-21.6%', '35,900', 'Midland, Michigan']
Extracted data: ['100', 'Best Buy', 'Retail', '43,452', '-6.1%', '85,000', 'Richfield, Minnesota']

In [79]:
# Remove the 'Revenue growth' header if it's not needed in the data
if 'Revenue growth' in world_tables_titles:
    world_tables_titles.remove('Revenue growth')

In [82]:
headers = ['Rank', 'Name', 'Industry', 'Revenue(USD millions)', 'Revenue growth', 'Employees', 'Headquarters']
import pandas as pd

# Create a DataFrame using the extracted data
df_data = pd.DataFrame(data_rows[1:], columns=headers)  # Skip the first row if it's headers

# Display the DataFrame
print(df_data)

   Rank                                 Name  \
0     1                              Walmart
1     2                               Amazon
2     3                                Apple
3     4                   UnitedHealth Group
4     5                   Berkshire Hathaway
5     6                           CVS Health
6     7                           ExxonMobil
7     8                             Alphabet
8     9                 McKesson Corporation
9    10                              Cencora
10   11                               Costco
11   12                       JPMorgan Chase
12   13                            Microsoft
13   14                      Cardinal Health
14   15                  Chevron Corporation
15   16                                Cigna
16   17                   Ford Motor Company
17   18                      Bank of America
18   19                       General Motors
19   20                      Elevance Health
20   21                            Citigroup
21   22                              Centene
22   23                       The Home Depot
23   24                   Marathon Petroleum
24   25                               Kroger
25   26                          Phillips 66
26   27                           Fannie Mae
27   28             Walgreens Boots Alliance
28   29                        Valero Energy
29   30                       Meta Platforms
30   31               Verizon Communications
31   32                                 AT&T
32   33                              Comcast
33   34                          Wells Fargo
34   35                        Goldman Sachs
35   36                          Freddie Mac
36   37                   Target Corporation
37   38                               Humana
38   39                           State Farm
39   40                                Tesla
40   41                       Morgan Stanley
41   42                    Johnson & Johnson
42   43               Archer Daniels Midland
43   44                              PepsiCo
44   45                United Parcel Service
45   46                                FedEx
46   47              The Walt Disney Company
47   48                    Dell Technologies
48   49                               Lowe's
49   50                     Procter & Gamble
50   51             Energy Transfer Partners
51   52                               Boeing
52   53                           Albertsons
53   54                                Sysco
54   55                      RTX Corporation
55   56                     General Electric
56   57                      Lockheed Martin
57   58                     American Express
58   59                          Caterpillar
59   60                              MetLife
60   61                       HCA Healthcare
61   62              Progressive Corporation
62   63                                  IBM
63   64                           John Deere
64   65                               Nvidia
65   66                         StoneX Group
66   67                          Merck & Co.
67   68                       ConocoPhillips
68   69                               Pfizer
69   70                      Delta Air Lines
70   71                            TD Synnex
71   72                               Publix
72   73                             Allstate
73   74                                Cisco
74   75  Nationwide Mutual Insurance Company
75   76               Charter Communications
76   77                               AbbVie
77   78      New York Life Insurance Company
78   79                                Intel
79   80                                  TJX
80   81                 Prudential Financial
81   82                                   HP
82   83                      United Airlines
83   84               Performance Food Group
84   85                          Tyson Foods
85   86                    American Airlines
86   87                       Liberty Mutual
87   88                                 Nike
88   89                   Oracle Corporation
89   90                  Enterprise Products
90   91                Capital One Financial
91   92         Plains All American Pipeline
92   93             World Kinect Corporation
93   94                                  AIG
94   95                            Coca-Cola
95   96                                 TIAA
96   97                                  CHS
97   98                 Bristol-Myers Squibb
98   99                 Dow Chemical Company
99  100                             Best Buy

                              Industry Revenue(USD millions) Revenue growth  \
0                               Retail               648,125           6.0%
1            Retail andcloud computing               574,785          11.9%
2                 Electronics industry               383,482          -2.8%
3                           Healthcare               371,622          14.6%
4                         Conglomerate               364,482          20.7%
5                           Healthcare               357,776          10.9%
6                   Petroleum industry               344,582         -16.7%
7        Technologyand cloud computing               307,394           8.7%
8                               Health               276,711           4.8%
9                   Pharmacy wholesale               262,173           9.9%
10                              Retail               242,290           6.8%
11                  Financial services               239,425          54.7%
12      Technology and cloud computing               211,915           6.9%
13                          Healthcare               205,012          13.0%
14                  Petroleum industry               200,949         -18.4%
15                    Health insurance               195,265           8.2%
16                 Automotive industry               176,191          11.5%
17                          Financials               171,912          49.4%
18                 Automotive industry               171,842           9.6%
19                          Healthcare               171,340           9.4%
20                          Financials               156,820          55.1%
21                          Healthcare               153,999           6.5%
22                              Retail               152,669          -3.0%
23                  Petroleum industry               150,307         -16.5%
24                              Retail               150,039          -3.6%
25                  Petroleum industry               149,890         -14.7%
26                          Financials               141,240          16.2%
27             Pharmaceutical industry               139,081           4.8%
28                  Petroleum industry               139,001         -18.8%
29                          Technology               134,902          15.7%
30                  Telecommunications               133,974          -2.1%
31  Conglomerateand telecommunications               122,428           1.4%
32                  Telecommunications               121,572           0.1%
33                          Financials               115,340          39.2%
34                          Financials               108,418          57.8%
35                          Financials               108,050          24.6%
36                              Retail               107,412          -1.6%
37                    Health insurance               106,374          14.5%
38                          Financials               104,199          16.6%
39               Automotive and energy                96,773          18.8%
40                          Financials                96,194          45.9%
41             Pharmaceutical industry                95,195           0.3%
42                       Food industry                93,935          -7.5%
43                            Beverage                91,471           5.9%
44                      Transportation                90,958          -9.3%
45                      Transportation                90,155          -3.6%
46                               Media                88,898           7.5%
47                          Technology                88,425         -13.6%
48                              Retail                86,377         -11.0%
49     Consumer products manufacturing                82,006           2.3%
50                  Petroleum industry                78,586         -12.6%
51                 Aerospaceanddefense                77,794          16.8%
52                              Retail                77,650           8.0%
53                        Food service                76,325          11.2%
54                        Conglomerate                68,920           2.8%
55                        Conglomerate                67,954         -11.2%
56               Aerospace and defense                67,571           2.4%
57                           Financial                67,364          21.1%
58                           Machinery                67,060          12.8%
59                          Financials                66,905          -4.3%
60                          Healthcare                64,968           7.9%
61                           Insurance                62,109          25.2%
62      Technology and cloud computing                61,860         -16.3%
63           Agriculture manufacturing                61,251          16.5%
64                          Technology                60,922         125.9%
65                          Financials                60,856          -7.8%
66             Pharmaceutical industry                60,115           1.4%
67                  Petroleum industry                58,574         -28.7%
68             Pharmaceutical industry                58,496         -41.7%
69                             Airline                58,048          14.8%
70                            Infotech                57,555          -7.7%
71                              Retail                57,534           4.7%
72                           Insurance                57,094          11.1%
73      Telecom hardware manufacturing                56,998          10.6%
74                           Financial                54,609           6.1%
75                  Telecommunications                54,607           1.1%
76             Pharmaceutical industry                54,317          -6.4%
77                           Insurance                54,317          14.2%
78                          Technology                54,228         -14.0%
79                              Retail                49,936           2.9%
80                          Financials                53,979         -10.1%
81                          Technology                53,718         -14.5%
82                             Airline                53,717          19.5%
83                     Food processing                53,355          13.1%
84                     Food processing                52,788          -0.8%
85                             Airline                52,788           7.8%
86                           Insurance                52,612           5.3%
87                             Apparel                51,217           9.6%
88                          Technology                49,954          17.7%
89                  Petroleum industry                49,715         -14.6%
90                          Financials                49,484          29.0%
91                  Petroleum industry                48,712         -15.1%
92                      Energy trading                47,711         -19.2%
93                           Insurance                46,802         -17.1%
94                            Beverage                45,754           6.4%
95                          Financials                45,735          11.8%
96             Agriculture cooperative                45,590          -4.6%
97             Pharmaceutical industry                45,006          -2.5%
98                   Chemical industry                44,622         -21.6%
99                              Retail                43,452          -6.1%

    Employees                                Headquarters
0   2,100,000                       Bentonville, Arkansas
1   1,525,000                         Seattle, Washington
2     161,000                       Cupertino, California
3     440,000                       Minnetonka, Minnesota
4     396,500                             Omaha, Nebraska
5     259,500                    Woonsocket, Rhode Island
6      61,500                               Spring, Texas
7     182,502                   Mountain View, California
8      48,000                               Irving, Texas
9      44,000                  Conshohocken, Pennsylvania
10    316,000                        Issaquah, Washington
11    309,926                     New York City, New York
12    221,000                         Redmond, Washington
13     47,520                                Dublin, Ohio
14     45,600                       San Ramon, California
15     71,413                     Bloomfield, Connecticut
16    177,000                          Dearborn, Michigan
17    212,985                   Charlotte, North Carolina
18    163,000                           Detroit, Michigan
19    104,900                       Indianapolis, Indiana
20    237,925                     New York City, New York
21     67,700                         St. Louis, Missouri
22    463,100                            Atlanta, Georgia
23     18,200                               Findlay, Ohio
24    414,000                            Cincinnati, Ohio
25     14,000                              Houston, Texas
26      8,100                            Washington, D.C.
27    268,500                         Deerfield, Illinois
28      9,987                          San Antonio, Texas
29     67,317                      Menlo Park, California
30    105,400                     New York City, New York
31    150,470                               Dallas, Texas
32    186,000                  Philadelphia, Pennsylvania
33    226,000                   San Francisco, California
34     45,300                     New York City, New York
35      8,020                            McLean, Virginia
36    415,000                      Minneapolis, Minnesota
37     67,600                        Louisville, Kentucky
38     65,054                       Bloomington, Illinois
39    140,473                               Austin, Texas
40     80,006                     New York City, New York
41    131,900                   New Brunswick, New Jersey
42     41,008                           Chicago, Illinois
43    318,000                          Purchase, New York
44    382,550                            Atlanta, Georgia
45    446,400                          Memphis, Tennessee
46    199,125                         Burbank, California
47    120,000                           Round Rock, Texas
48    226,000                 Mooresville, North Carolina
49    107,000                            Cincinnati, Ohio
50     13,786                               Dallas, Texas
51    171,000                  Arlington County, Virginia
52    198,650                                Boise, Idaho
53     71,750                              Houston, Texas
54    185,000                  Arlington County, Virginia
55    125,000                       Boston, Massachusetts
56    122,000                          Bethesda, Maryland
57     74,600                     New York City, New York
58    113,200                         Deerfield, Illinois
59     45,000                     New York City, New York
60    265,000                        Nashville, Tennessee
61     61,432                      Mayfield Village, Ohio
62    296,600                            Armonk, New York
63     82,956                            Moline, Illinois
64     29,600                     Santa Clara, California
65      4,137                     New York City, New York
66     71,000                      Kenilworth, New Jersey
67      9,900                              Houston, Texas
68     88,000                     New York City, New York
69    103,000                            Atlanta, Georgia
70     28,000                         Clearwater, Florida
71    253,000                           Lakeland, Florida
72     53,200  Northfield Township, Cook County, Illinois
73     84,900                        San Jose, California
74     24,118                              Columbus, Ohio
75    101,100                       Stamford, Connecticut
76     50,000                        Lake Bluff, Illinois
77     15,384                     New York City, New York
78    124,800                     Santa Clara, California
79    329,000                   Framingham, Massachusetts
80     40,366                          Newark, New Jersey
81     58,000                       Palo Alto, California
82    103,300                           Chicago, Illinois
83     34,825                          Richmond, Virginia
84    139,000                        Springdale, Arkansas
85    132,100                           Fort Worth, Texas
86     45,000                       Boston, Massachusetts
87     83,700                           Beaverton, Oregon
88    164,000                               Austin, Texas
89      7,500                              Houston, Texas
90     51,987                          Richmond, Virginia
91      4,200                              Houston, Texas
92      5,289                               Doral,Florida
93     25,200                     New York City, New York
94     79,100                            Atlanta, Georgia
95     16,023                     New York City, New York
96     10,609              Inver Grove Heights, Minnesota
97     34,100                      New York City,New York
98     35,900                           Midland, Michigan
99     85,000                        Richfield, Minnesota

In [83]:
# Display the first few rows
print(df_data.head())

# Check DataFrame shape
print(f"DataFrame shape: {df_data.shape}")

# Check if any columns contain missing values
print(df_data.isnull().sum())

  Rank                Name                   Industry Revenue(USD millions)  \
0    1             Walmart                     Retail               648,125
1    2              Amazon  Retail andcloud computing               574,785
2    3               Apple       Electronics industry               383,482
3    4  UnitedHealth Group                 Healthcare               371,622
4    5  Berkshire Hathaway               Conglomerate               364,482

  Revenue growth  Employees           Headquarters
0           6.0%  2,100,000  Bentonville, Arkansas
1          11.9%  1,525,000    Seattle, Washington
2          -2.8%    161,000  Cupertino, California
3          14.6%    440,000  Minnetonka, Minnesota
4          20.7%    396,500        Omaha, Nebraska
DataFrame shape: (100, 7)
Rank                     0
Name                     0
Industry                 0
Revenue(USD millions)    0
Revenue growth           0
Employees                0
Headquarters             0
dtype: int64

In [ ]:
df_data.to_csv('s3://hpicommercialpc/prod/data/work/saketh/Data/largest_companies_2024.csv', index=False)